# Generated by Django 5.1.3 on 2024-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Usuario", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254)),
                ("Senha", models.CharField(max_length=50)),
            ],
        ),
    ]
